version: '3'
services:
    server:
      build: .
      command:
         python3 manage.py runserver 0.0.0.0:8000
      depends_on:
        - db
      #useful in development to track the changes
      volumes:
        - ./product_seller:/code
      ports:
        - "8000:8000"
      env_file:
        - .env
      networks:
        - server_network
    db:
      image: postgres
      container_name: db
      ports:
        - "5438:5432"
      environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - ALLOW_IP_RANGE=0.0.0.0
      volumes:
        - postgres_data:/var/lib/postgresql
      networks:
        - server_network


networks:
  server_network:
    driver: bridge

volumes:
  postgres_data:
